# Configurações do repositório GitHub
repository:
  name: america-vendas
  description: "Plataforma moderna para anúncios de imóveis e veículos"
  homepage: "https://america-vendas.vercel.app"
  topics: "react,typescript,vite,supabase,stripe,marketplace,real-estate,vehicles"
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: "main"
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true 